# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: 'Export Actions Env'
description: "GitHub Action to expose GitHub actions env vars to the workflow"
author: 'wankdanker'
branding:
  color: 'red'
  icon: 'eye'

inputs:
  github-token:
    description: 'GitHub Token as provided by secrets'
    default: ${{ github.token }}
    required: true

runs:
  using: 'node16'
  main: 'index.js'
